name: Build Emacs
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: test/Dockerfile-xenial
          tags: emacs_xenial
      - run: |
          docker run emacs_xenial /usr/local/bin/emacs --version
